### ISSUE TITLE
Problems for running the code

### ISSUE THREAD

**Issue by Rivendile** [mfranzs/meta-learning-curiosity-algorithms#2]
This work is impressive and we would like to reproduce your result and compare it in our study. I run the code with python 3.7.7.
1. Could you please tell me which experiment id for program_synthesis.py and test_synthesized_programs.py did you use for 4.1/4.2 in your ICLR paper?
2. When I run test_synthesized_programs.py, "File "/home/wuruihai/ZYH/mlca/run_agent.py", line 98, in evaluate_program_in_environment. AttributeError: module 'mlca.helpers.debug' has no attribute 'Profiler'" occurs. And I checked that there is no Profiler in mlca.helpers.debug. Could you please tell me how to fix this error?
3. I have also found that there is no ProgramType defined in program_type.py, which doesn't affect running the code.

**Comment by mfranzs** [comment]
Thanks for your interest!

1. I believe the experiment IDs are `2-98_acrobot_new_atari-ppo-real-batched-shared_7500-steps_2-trials-yes-share-yes-batch-1_steps_curiosity` and `2-100_lunar_lander_new_atari-ppo-real-batched-shared_7500-steps_2-trials-yes-share-yes-batch-1_steps_curiosity` for acrobot and lunar lander respectively.

2. Good point - this was an omission on our part. I have copied the Profiler class back in, so it should be working now.

3.  Thanks! This was another error in compiling this published version of the code. This should also be fixed now.

**Comment by Rivendile** [comment]
Thanks for your reply!
